config/routes.rb
Vitae::Application.routes.draw do

  get "sessions/new"

  get "users/new"

root :to => 'openings#index'
match '/openings/admin', :to => 'openings#admin'
match '/openings/show_report', :to => 'openings#show_report'
resources :openings
resources :users
resources :sessions, :only => [:new, :create, :destroy]
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/opening.rb
class Opening < ActiveRecord::Base
  attr_accessible :position, :objective, :grizzard, :skill, :company, :pid
  validates :pid, :presence => true,
  				  :uniqueness => true
 # has_friendly_id :name, :use_slug => true				  
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
 # attr_accessor :name, :email
 attr_accessor :password
 attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
  				   :length => { :maximum => 50 }
  validates :email, :presence => true,
  				  	:format => { :with => email_regex },
					:uniqueness => { :case_insensitive => false }
  # Automatically create the virtual attirbute 'password_confirmation'
  validates :password,  :presence     => true,
  						:confirmation => true,
  						:length		  => { :within => 6..40 }

  before_save :encrypt_password
  
  # return true if the user;s password matches the submitted pw.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password) # Compare encrypted_password with the encrypted versionf of submitted pw.
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#(salt)--#(string)")
    end
    
    def make_salt
      secure_hash("#(Time.now.utc--#(password)")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

  				  	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  include SessionsHelper
  
  def title
    base_title = "Sam W. Walton"
    if @title.nil?
      base_title
    else
      # "#{base_title} | #{@title}"
    end
  end
  
end

app/controllers/openings_controller.rb
class OpeningsController < ApplicationController

  def index
    #@opening = Opening.all
    #@opening = params[:pid]
    @opening = Opening.find(:all)
  end
  
  def admin
    #@opening = Opening.all
    #@opening = params[:pid]
    @opening = Opening.find(:all)
  end
  
  def show
    @opening = Opening.find(params[:id])
    @title = @opening.position
    
    #if @opening?
      respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @opening }
        format.json { render :json => @opening }
      end
    # else
     #  render :template => "openings/error"
     
   # end
  end
  
  def new
    @opening = Opening.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @opening }
    end
  end
  
  def create
    @opening = Opening.new(params[:opening])

    respond_to do |format|
      if @opening.save
        #redirect_to("/#{@opening.pid}", :notice => 'Opening was created.')
        format.html { redirect_to(@opening, :notice => 'Opening was successfully created.') }
        #format.html { redirect_to opening_path(@opening.id), :notice => 'Opening was successfully created.' }
        format.xml  { render :xml => @opening, :status => :created, :location => @opening }
        format.json  { render json: @opening, status: :created, location: @opening }
     else
        format.html { render :action => "new" }
        format.xml  { render :xml => @opening.errors, :status => :unprocessable_entity }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @opening = Opening.find(params[:id])
  end
  

  def update
    #@opening = Opening.find(params[:opening]) because form_for is pulling convention.
    @opening = Opening.find(params[:id])
#debugger
    respond_to do |format|
      if @opening.update_attributes(params[:opening]) # not :id
        #redirect_to("/#{@opening.pid}", :notice => 'Opening was created.')
        #format.html { redirect_to(@opening, :notice => 'Opening was successfully created.') }
        format.html { redirect_to opening_path(@opening.id), :notice => 'Opening was updated.' }
        format.xml  { render :xml => @opening, :status => :created, :location => @opening }
      else
        format.html { render :action => "/openings/edit/:pid" }
        format.xml  { render :xml => @opening.errors, :status => :unprocessable_entity }
      end
    end
  end
 # /openings/:id
  def show_report
    @opening=Opening.find(:all)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
    						 params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
     sign_in user
     redirect_back_or user
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
    @title = "All users"
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save # handle a successful save
      sign_in @user
      flash[:success] = "Welcome to Vitae"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def edit
    #@user = User.find(params[:id])
    @title = "Edit user"
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  private
  
    def authenticate
      deny_access unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Vita: Sam Walton" 
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/chairs_helper.rb
module ChairsHelper
end

app/helpers/developer_helper.rb
module DeveloperHelper
end

app/helpers/opening_helper.rb
module OpeningHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/helpers/position_helper.rb
module PositionHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  def current_user=(user)
    #user == current_user
    @current_user = user #this is suspect
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def current_user?(user)
		user == current_user
  end
	
  private
  
    # Authenticates user using remember token rather than email and password
	# using authenticate_with_salt.
	def user_from_remember_token
		User.authenticate_with_salt(*remember_token)
	end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_background.html.erb
  <div class="span-18 last" id="background"> 
<div id="address"  class="span-11"> 
<p class="tight">Sam Walton</p> 
<p class="tight">7540 Harper Rd</p> 
<p class="tight">Joelton, TN 37080, near Nashville, TN</p> 
<p class="tight">615-495-7783 &bull; sam@samwalton.me</p> 
</div>
</div> 

app/views/layouts/_header.html.erb
<header>
  <%= link_to root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html> 
<head>
  <title><%= title %></title>
  <%= render  'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tags %>
</head>
<body > 
<div class="container">
</div>  
<section>
    <%= flash.each do |key, value| %>
      <%= content_tag(:div, value, :class => "flash #{key}") %>
    <% end %>
    <%= yield %>
  <%= debug(params) if Rails.env.development? %>
  </section>




</body>
</html>

app/views/openings/admin.html.erb
<h1>Listing Openings</h1>

  <div id="header" class="span-23 last">
  <%= render 'layouts/header' %>
    <nav class="round">
    
    </nav>
  </header>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @opening.each do |opening| %>
  <tr>
    <td><%= link_to 'Show', opening %></td>
    <td><%= opening.pid %></td>
    <td><%= link_to 'Edit', edit_opening_path(opening) %></td>
    <td><%= link_to 'Destroy', opening, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Opening', new_opening_path %>

app/views/openings/edit.html.erb
<div class="span-11 last" id="background"> 
<%= form_for (@opening)  do |f| %>
  <div class="field">
    <%= f.label :compan1, "Company applied for." %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :position, "Proper name  of position" %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :objective, "Objective" %><br />
    <%= f.text_field :objective %>
  </div>
    <div class="field">
    <%= f.label :pid, "Unique ID" %><br />
    <%= f.text_field :pid %>
  </div>
 <div class="field">
    <%= f.label :grizzard, "Relevant Grizzard experience" %><br />
    <%= f.text_area :grizzard %>
  </div>
 <div class="field">
    <%= f.label :skill, "Relevant skills to highlight" %><br />
    <%= f.text_area :skill %>
  </div>
 <div class="actions">
    <%= f.submit "Check in" %>
  </div>
<% end %>
</div>

app/views/openings/error.html.erb
<h1> Error</h1>

app/views/openings/index.html.erb
<div class="span-11 push-2 last subhed" id="background"> Thank you for visiting samwalton.me.</p>
<p span class="small">To view the current vita, you must have been given a custom website. Perhaps
it was mis-keyed? If you're not sure, call the phone number above.</span></p>

<img align     = "center"
     alt       = "Sam W. Walton"
     height    = "409px"
     hspace    = "0"
     src       = "sam-w-1.gif"
     width     = "391px"
     />
     </div>

app/views/openings/new.html.erb
<div class="span-11 last" id="background"> 

  <div id="header" class="span-23 last">
  <%= render 'layouts/header' %>
    <nav class="round">
    
    </nav>
  </header>
  <% if @opening.errors.any? %>
    <div class="alert-message block-message error">
      <p><strong>You got an error!</strong></p>
      <ul>
        <% @opening.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>    
    </div>
  <% end %>
  
<%= form_for (@opening)  do |f| %>
  <div class="field">
    <%= f.label :company, "Company applied for." %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :position, "Proper name  of position" %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :objective, "Objective" %><br />
    <%= f.text_area :objective %>
  </div>
    <div class="field">
    <%= f.label :pid, "Unique ID" %><br />
    <%= f.text_field :pid %>
  </div>
 <div class="field">
    <%= f.label :grizzard, "Relevant Grizzard experience" %><br />
    <%= f.text_area :grizzard %>
  </div>
 <div class="field">
    <%= f.label :skill, "Relevant skills to highlight" %><br />
    <%= f.text_area :skill %>
  </div>
 <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>
</div>

app/views/openings/show.html.erb
<%= render  'layouts/background' %>

<p id="notice"><%= notice %></p>
<div id="objective" class="span-18 last">
<p class="subhed centre tight">Career Objective</p>
<p class="base"><%= @opening.objective %></p>
</div>
<div id="experience" class="span-18 last">
<p class="subhed centre tight">Experience</p>
<!-- <div id="recent" class="span-18 last"> -->
<p class="subhed tight">Grizzard, Inc., Atlanta, Ga.</p>
<p class="base prepend-1"><%=raw simple_format h(@opening.grizzard)  %></p>
<!-- </div> -->
<p class="subhed tight">Panaprint, Inc., Macon, Ga.</p>
<p class="base">Composition Department manager from January 1994 to January 1995. I took over management of this five-person team responsible for handling customer artwork and turning it into error-free output for this 45-person commercial printing plant. My task was to eliminate bottlenecks and help the team to use untapped capabilities in the new systems. The goal was achieved when productivity increased by 25 percent and meeting 95 per cent of the deadlines.</p>
<p class="subhed tight">The Union-Recorder, Milledgeville, Ga.</p>
<p class="base leftedge">News Editor of Page 1A and related news pages for this 8,5000-circulation five-day morning Knight-Ridder newspaper from 1993 to 1994. To get to this position, I taught myself to use the new Macintosh and PC software to advance the newspaper to pagination integrating text, artwork and photos. This was an outgrowth of my career as a photojournalist from 1986.</p>
<p class="subhed tight">The Gwinnett Daily News, Lawrenceville, Ga.</p>
<p class="base leftedge">Staff photographer from October 1985 to February 1986 for this 33,000-circulation daily morning newspaper. Work included full range of news, sports and feature photojournalism, in color and black and white.</p>
<p class="subhed tight">Experience prior to graduation</p>
<p class="base"><b>The Atlanta Journal and Constitution, </b>Atlanta, Ga. – Covered Northeast Georgia on assignment basis while a student for two years, except time on intern programs for this 250,000-circulation daily morning and afternoon paper. Was assigned a UPI photo transmitter in Athens, Ga.</p>
<p class="base"><b>The Chattanooga Times,</b> Chattanooga, Tenn. – Student intern with full responsibilities as a photographer.</p>
<p class="base"><b>The Florida Times-Union,</b> Jacksonville, Fla. – Student intern with full responsibilities as a photographer.</p>
<p class="base"><b>The Red and Black,</b> Athens, Ga. – Photo editor for daily student newspaper from 1981 to 1983.</p>
<p class="base"><b>The Leader-Tribune,</b> Fort Valley, Ga. – Staff photographer, darkroom manager from 1975 to 1981.</p>
</div>
<div id="skills" class="span-18 last">
<p class="head centre tight"><b>Skills</b></p>
<p class="span-18 last tight"><%=raw simple_format h(@opening.skill)  %></p>
</div>
<div id="education" class="span-18 last">
<p class="head centre tight"><b>Education</b></p>
<p class="base 24-span last">Graduated June 1985 from Henry W. Grady School of Journalism and Mass Communications, University of Georgia, with a major in newspapers and a minor in Religion. Earned 50 percent of college expenses as photojournalist.</p>
<p class="head centre tight"><b>References</b></p>
</div>
<div id="references" class="span-18 last">
<p class="base">Judy Howard, Production Manager, Grizzard, Atlanta, Ga. (404) 935-7121 (Recent supervisor)</p>
<p class="base">Ron Thurmond, Controller, Grizzard, Atlanta, Ga. (404) 635-5731 (former Controller)</p>
<p class="base">Clyde Tallent, Grizzard, Atlanta, Ga. (404) 428-1972 (peer supervisor)</p>
<p class="base">Stuart Scruggs, Ivey Construction, Stone Mountain, Ga. (404) 771-7812 (personal friend)</p>
</div>
 
<!-- 
<div id="bug" class="span-4 last">

 <table>
 	<tr>
 		<td class="bug span-2"><a href="../print.css">Click here to display a copy ready to print.</a></td>
 		<td class="space span-6"></td>
 	</tr>
 </table>
</div>
 -->

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
  | <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{user.name}" %>
  <% end %>
</li>

app/views/users/edit.html.erb
  <div id="header" class="span-23 last">
  <%= render 'layouts/header' %>
    <nav class="round">
    
    </nav>
  </header>

<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
  <div id="header" class="span-23 last">
  <%= render 'layouts/header' %>
    <nav class="round">
    
    </nav>
  </header>

<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
  <div id="header" class="span-23 last">
  <%= render 'layouts/header' %>
    <nav class="round">
    
    </nav>
  </header>
<div class="span-11 last" id="background"> 

  <% if @user.errors.any? %>
    <div class="alert-message block-message error">
      <p><strong>You got an error!</strong></p>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>    
    </div>
  <% end %>
  
<%= form_for (@user)  do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
  <div id="header" class="span-23 last">
  <%= render 'layouts/header' %>
    <nav class="round">
    
    </nav>
  </header>
<h1>
<%= @user.name %>, <%= @user.email %>
</h1>